"""migration

Revision ID: 51c484cbb948
Revises: 8b899a714b5b
Create Date: 2024-10-17 10:20:29.070766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c484cbb948'
down_revision = '8b899a714b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('review_dates')
        batch_op.drop_column('reviewer_names')
        batch_op.drop_column('review_texts')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('review_product_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_foreign_key('review_product_id_fkey', 'product', ['product_id'], ['id'])
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_texts', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reviewer_names', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('review_dates', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
