"""migration

Revision ID: 726d20119b39
Revises: f0a447bbb692
Create Date: 2024-10-17 01:09:01.900140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726d20119b39'
down_revision = 'f0a447bbb692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratings', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('review_texts', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('review_dates', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reviewer_names', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('reviewer_names')
        batch_op.drop_column('review_dates')
        batch_op.drop_column('review_texts')
        batch_op.drop_column('ratings')

    # ### end Alembic commands ###
