"""review added

Revision ID: 86faf778a505
Revises: 6a5b9d7a6b26
Create Date: 2024-10-16 17:32:32.462824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86faf778a505'
down_revision = '6a5b9d7a6b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_text', sa.String(), nullable=True),
    sa.Column('reviewer_name', sa.String(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
