"""page table added

Revision ID: f0a447bbb692
Revises: 86faf778a505
Create Date: 2024-10-16 17:55:01.088119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a447bbb692'
down_revision = '86faf778a505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('last_page_scraped', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('last_page_scraped')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    # ### end Alembic commands ###
